apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-web-demo
  labels:
    app: tomcat-app
spec:
  replicas: 1
  selector: 
    matchLabels: 
       app: tomcat-app
  template:
    metadata:
      name: tomcat-web-demo
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat-web-demo
          image: demo2
          imagePullPolicy: Never
          ports:
           - containerPort: 8080