apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-web
  labels:
    app: tomcat-app
spec:
  replicas: 1
  selector: 
    matchLabels: 
       app: tomcat-app
       tier: backend
  template:
    metadata:
      name: tomcat-web
      labels:
        app: tomcat-app
        tier: backend
    spec:
      containers:
        - name: tomcat-web
          image: tomcat-web
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
           - containerPort: 8080
